/*
 https://github.com/Arthur18aa/3IV9_Andrade_Aguilar_Arturo_Imanol.git
https://github.com/CesaRLB17/3IV9-Lopez-Bastida-Cesar-Ricardo.git
 */
package Principal;

import LindoMinino.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andra
 */
public class Lobby extends javax.swing.JFrame {
            
            DefaultTableModel md;
            String datos[][]={};
            String cabeza []={"NOMBRE", "EDAD", "PUNTUACIÓN"};

            
    /**
     * Creates new form Lobby
     */
    public Lobby() {
        initComponents();
        md = new DefaultTableModel(datos, cabeza);
        jTablaDatos.setModel(md);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jEmpezar = new javax.swing.JButton();
        jGuardar = new javax.swing.JButton();
        jSalir = new javax.swing.JButton();
        jPlayer1 = new javax.swing.JLabel();
        jNombre1 = new javax.swing.JTextField();
        jEdad1 = new javax.swing.JLabel();
        jTFEdad1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaDatos = new javax.swing.JTable();
        jPuntu = new javax.swing.JLabel();
        jPuntuacion1 = new javax.swing.JTextField();
        jEliminar = new javax.swing.JButton();
        jModificar = new javax.swing.JButton();
        jFilis = new javax.swing.JLabel();
        jColumbus = new javax.swing.JLabel();
        jFila = new javax.swing.JTextField();
        jColumna = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jNuevoDato = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 102, 255));

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jEmpezar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jEmpezar.setText("COMENZAR JUEGO");
        jEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmpezarActionPerformed(evt);
            }
        });
        jPanel1.add(jEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 400, 90));

        jGuardar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jGuardar.setText("GUARDAR DATOS");
        jGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 250, 100));

        jSalir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jSalir.setText("SALIR");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 450, 140, 110));

        jPlayer1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPlayer1.setText("Player:");
        jPanel1.add(jPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, 90));

        jNombre1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombre1ActionPerformed(evt);
            }
        });
        jPanel1.add(jNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 180, 50));

        jEdad1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jEdad1.setText("Edad:");
        jPanel1.add(jEdad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, 80));

        jTFEdad1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jTFEdad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 70, 60));

        jTablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablaDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 550, 250));

        jPuntu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPuntu.setText("Puntuación:");
        jPanel1.add(jPuntu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jPuntuacion1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPuntuacion1.setText("0");
        jPanel1.add(jPuntuacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 70, 60));

        jEliminar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jEliminar.setText("ELIMINAR");
        jEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 200, 100));

        jModificar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jModificar.setText("MODIFICAR");
        jModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 190, 100));

        jFilis.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jFilis.setText("Fila:");
        jPanel1.add(jFilis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jColumbus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jColumbus.setText("Columna:");
        jPanel1.add(jColumbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jFila.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 60, 40));

        jColumna.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jColumna.setText("2");
        jColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColumnaActionPerformed(evt);
            }
        });
        jPanel1.add(jColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 40, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nueva Puntuación:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jNuevoDato.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jNuevoDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 60, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Hola Gamer, en este juego eres el responsable de que");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 520, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText(" las puntuaciones sean correctas, procura no hacer trampa.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel4.setText("Las filas empiezan su cuenta desde el 0, la columna 2 es automática para ingresar de ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 500, 20));

        jLabel5.setText("manera rápida los puntajes, si deseas cambiar algún dato también se cuenta desde 0");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        jLabel6.setText("columna. Disfruta el juego.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Juego Realizado por Arturo Imanol Andrade Aguilar y Cesar Ricardo López Bastida");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmpezarActionPerformed

        Miauu m = new Miauu();
        m.setVisible(true);
    }//GEN-LAST:event_jEmpezarActionPerformed

    
private JFrame frame;


    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
         
            
            frame = new JFrame("Salir");
            
            if (JOptionPane.showConfirmDialog(frame, "Confirma si quieres salir del Lobby","Gato",
                    JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION);
        
        {
            System.exit(0);
        }
        
    }//GEN-LAST:event_jSalirActionPerformed

    private void jNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNombre1ActionPerformed

    private void jGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarActionPerformed
            
            String nombre1=jNombre1.getText();
            String edad1=jTFEdad1.getText();
            String puntuacion1=jPuntuacion1.getText();
            
           String datos []={nombre1, edad1, puntuacion1};
            
            md.addRow(datos);
            
            
          
            
    }//GEN-LAST:event_jGuardarActionPerformed

    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarActionPerformed
        
        int fila=jTablaDatos.getSelectedRow();
            if (fila>=0){
                md.removeRow(fila);
                
            }else{
                JOptionPane.showMessageDialog(null, "Seleccionar Fila");
        }
    }//GEN-LAST:event_jEliminarActionPerformed

    private void jModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModificarActionPerformed
       
        int fila=Integer.parseInt(jFila.getText());
       int columna=Integer.parseInt(jColumna.getText());
       md.setValueAt(jNuevoDato.getText(),fila, columna);
             
    }//GEN-LAST:event_jModificarActionPerformed

    private void jColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColumnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jColumnaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jColumbus;
    private javax.swing.JTextField jColumna;
    private javax.swing.JLabel jEdad1;
    private javax.swing.JButton jEliminar;
    private javax.swing.JButton jEmpezar;
    private javax.swing.JTextField jFila;
    private javax.swing.JLabel jFilis;
    private javax.swing.JButton jGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jModificar;
    private javax.swing.JTextField jNombre1;
    private javax.swing.JTextField jNuevoDato;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPlayer1;
    private javax.swing.JLabel jPuntu;
    private javax.swing.JTextField jPuntuacion1;
    private javax.swing.JButton jSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFEdad1;
    private javax.swing.JTable jTablaDatos;
    // End of variables declaration//GEN-END:variables
}
